name: Build and deploy React app to Azure Web App
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm
 
      - name: Install dependencies
        run: npm install
 
      - name: Build React app
        run: npm run build
 
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
 
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
 
    permissions:
      id-token: write
      contents: read
 
    steps:
 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
 
 
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80DDB670A42647598F04D79FB52B6C03 }}
          # tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2876D16797F541389A6B5FC3B4CFF3F6 }}
          # subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_304D34F5D9804AC4BDE98E5C8C5D66B5 }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80DDB670A42647598F04D79FB52B6C03 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2876D16797F541389A6B5FC3B4CFF3F6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_304D34F5D9804AC4BDE98E5C8C5D66B5 }}
 
      - name: Deploy React App
        uses: azure/webapps-deploy@v3
        with:
          app-name: payroll-system-app
          package: .